SUBROUTINE invertz(A,AINV,N)
IMPLICIT NONE
DOUBLE PRECISION, INTENT(IN) :: A(N,N)
DOUBLE PRECISION, INTENT(OUT) :: AINV(N,N)
INTEGER, INTENT(IN) :: N
INTEGER :: LDA, LWORK,INFO
DOUBLE PRECISION :: WORK(N)
INTEGER :: IPIV(N)

AINV = A

call DGETRF(N, N, AINV, N, IPIV, INFO)

CALL DGETRI( N, AINV, N, IPIV, WORK, N, INFO )


END SUBROUTINE invertz
