SUBROUTINE makedens(COEFF,NB,P)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NB
      DOUBLE PRECISION, INTENT(IN) :: COEFF(NB,NB)
      DOUBLE PRECISION, INTENT(OUT) :: P(NB,NB)

      P = MATMUL(COEFF,TRANSPOSE(COEFF))

END SUBROUTINE makedens
           


